DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS events;

--=================== таблица Пользователи
 CREATE TABLE IF NOT EXISTS users (
              user_id 	INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name		VARCHAR(250) NOT NULL,
              email 	VARCHAR(254) NOT NULL,
			  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
          );
COMMENT ON TABLE users IS 'Таблица хранит данные о пользователях';
COMMENT ON COLUMN users.user_id IS 'Уникальный идентификатор пользователя, первичный ключ';
COMMENT ON COLUMN users.name IS 'Имя';
COMMENT ON COLUMN users.email IS 'Электронная почта';

--=================== таблица Категории
 CREATE TABLE IF NOT EXISTS categories (
              id 		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name		VARCHAR(50) NOT NULL,
              CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
          );
COMMENT ON TABLE categories IS 'Таблица хранит категории событий';
COMMENT ON COLUMN categories.id IS 'Уникальный идентификатор категории, первичный ключ';
COMMENT ON COLUMN categories.name IS 'Название категории';

--=================== таблица с информацией о событиях
 CREATE TABLE IF NOT EXISTS events (
              id 		        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              initiator_id      INTEGER REFERENCES users (user_id) ON DELETE RESTRICT,
              annotation	    VARCHAR(2000) NOT NULL,
              category_id       INTEGER REFERENCES categories (id) ON DELETE RESTRICT,
              description       VARCHAR(7000) NOT NULL,
              event_date        TIMESTAMP NOT NULL,
              location_lat      DOUBLE PRECISION NOT NULL,
              location_lon      DOUBLE PRECISION NOT NULL,
              paid              BOOLEAN,
              participant_limit INTEGER  NOT NULL,
              request_moderation BOOLEAN,
              title             VARCHAR(120) NOT NULL,
              published_datetime TIMESTAMP NOT NULL,
              state             VARCHAR(20) NOT NULL,
              creation_date     TIMESTAMP NOT NULL
          );
COMMENT ON TABLE events IS 'Таблица хранит информацию о событиях';
COMMENT ON COLUMN events.id IS 'Уникальный идентификатор события, первичный ключ';
COMMENT ON COLUMN events.initiator_id IS 'Идентификатор пользователя-инициатора события';
COMMENT ON COLUMN events.annotation IS 'Краткое описание события';
COMMENT ON COLUMN events.category_id IS 'id категории к которой относится событие';
COMMENT ON COLUMN events.description IS 'Полное описание события';
COMMENT ON COLUMN events.event_date IS 'Дата и время на которые намечено событие';
COMMENT ON COLUMN events.location_lat IS 'Широта места проведения события';
COMMENT ON COLUMN events.location_lon IS 'Долгота места проведения события';
COMMENT ON COLUMN events.paid IS 'Нужно ли оплачивать участие в событии';
COMMENT ON COLUMN events.participant_limit IS 'Ограничение на количество участников. Значение 0 - означает отсутствие ограничения';
COMMENT ON COLUMN events.request_moderation IS 'Нужна ли пре-модерация заявок на участие. Если true, то все заявки будут ожидать подтверждения инициатором события. Если false - то будут подтверждаться автоматически.';
COMMENT ON COLUMN events.title IS 'Заголовок события';
COMMENT ON COLUMN events.published_datetime IS 'Дата и время публикации события';
COMMENT ON COLUMN events.state IS 'Состояние жизненного цикла события';
COMMENT ON COLUMN events.creation_date IS 'Дата и время создания события';

--=================== очищение данных на случай наличия в них старых тестовых данных
DELETE FROM events;
DELETE FROM categories;
DELETE FROM users;