--=================== таблица с информацией о запросах
 CREATE TABLE IF NOT EXISTS endpoint_hits (
              id 		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              app		VARCHAR(100) NOT NULL,
              uri 	    VARCHAR(100) NOT NULL,
              ip 	    VARCHAR(39) NOT NULL,
              hit_datetime TIMESTAMP
          );
COMMENT ON TABLE endpoint_hits IS 'Таблица хранит информацию об запросах на эндпоинты';
COMMENT ON COLUMN endpoint_hits.id IS 'Уникальный идентификатор запроса, первичный ключ';
COMMENT ON COLUMN endpoint_hits.app IS 'Идентификатор сервиса для которого записывается информация';
COMMENT ON COLUMN endpoint_hits.uri IS 'URI для которого был осуществлен запрос';
COMMENT ON COLUMN endpoint_hits.ip IS 'IP-адрес пользователя, осуществившего запрос';
COMMENT ON COLUMN endpoint_hits.hit_datetime IS 'Дата и время, когда был совершен запрос к эндпоинту';

--=================== очищение данных на случай наличия в них старых тестовых данных
DELETE FROM endpoint_hits;